Integration specs
Luchy-B/blogapp pull request #9
Opened 2023-06-28 12:39 UTC by Luchy-B

- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
- Do not use the bullet gem in this exercise - instead analyze the logs as showed in this article

**Before:** 
![Post db4](https://github.com/Luchy-B/blogapp/assets/95630722/111cb370-df79-4ce0-976d-0c9d8265d72d)

![Post db 4b](https://github.com/Luchy-B/blogapp/assets/95630722/e03c6265-bb3b-402c-bcc8-5ac3045e459c)

**After**
![After](https://github.com/Luchy-B/blogapp/assets/95630722/62fb05d7-c441-4ac0-8d26-a4f796f95adc)

- User index page
- user show page:
- User post index page:
- post show page:

2023-06-29 11:35 UTC, rloterh requested changes
Hi Davian, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!
🏁 🚦 🏃 🌴 🏫 🌳 🏘️

## Highlights 👍  
- Nice job improving on the code!
- ReadMe looks great!

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's improve the look of the ReadMe by removing the underlined:

![image](https://github.com/Luchy-B/blogapp/assets/12745474/c7d6816e-a019-4a00-b40c-2822f248bbc3)


Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 11:35 UTC, rloterh commented on spec/integration_view/users/show_spec.rb
> +  end
- [ ] A test to assert that the scenario **_When I click a user's post, it redirects me to that post's show page_** for _user show view_ spec is missing! Please ensure to improve upon this aspect.

2023-06-29 11:35 UTC, rloterh commented on spec/integration_view/Post/index.html.erb_spec.rb
> +    end
- [ ] Let's also ensure to include tests for the below scenarios for _user index_ views: 
   * I can see a section for pagination if there are more posts than fit on the view
   * When I click on a post, it redirects me to that post's show page

2023-07-01 22:14 UTC, alexander16108 approved these changes
Hi @Luchy-B @imranhossainemi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif"/>

## Highlights
Nice job improving on the code!
ReadMe looks great!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 22:17 UTC, Luchy-B commented
Thank You for the Review

2023-07-01 22:17 UTC, merged